### ISSUE TITLE
CC65 - Run window not showing anything over v5.1.3

### ISSUE THREAD

**Issue by seanwiththebeard** [empathicqubit/vscode-cc65-debugger#104]
I'm having trouble getting the Run window tab to show anything on the recent update, it works when I revert to 5.1.3, using GTK Vice 3.6.1

**Comment by empathicqubit** [comment]
Hello seanwiththebeard,

did you see the Bug Report template when you created your issue? I need to know some more information and that had a number of questions on it that would have been helpful.

**Platform information (please complete the following information):**
Are you using VSCode or Codium?
Version:
```
Press Ctrl+Shift+P in Code and search for "About". Paste the version information.
```

What version of VICE are you using? (Help menu > About VICE)

Do you have cc65 installed separately or are you using the builtin one?
If you have it installed separately, be sure you are using the one with the changes from [empathicqubit/cc65](https://github.com/empathicqubit/cc65)

OS Type (Mac OS, Windows, Linux):
OS Version:
For Windows use `Reg Query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseId`
For Mac OS use `sw_vers`
For Linux use `lsb_release -a`

```
Use one of the above commands and paste the result here
```

OS Architecture (for example, amd64, i686, arm, arm64):

If you are able please provide your PATH:
For Windows (cmd) use `echo %PATH%`
For Mac OS/Linux use `echo $PATH`
Be sure to remove any information you consider sensitive. Replace it with REDACTED
```
Paste your PATH here
For example /usr/bin:REDACTED:/home/user/bin
```

Regards,
EQ

**Comment by empathicqubit** [comment]
Okay, I'm able to reproduce pretty easily on Windows. I'm unable to make automated tests for Windows, so thanks for reporting this.

**Comment by empathicqubit** [comment]
The issue should be fixed in
