### ISSUE TITLE
remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://deac-riga.dl.sourceforge.net/...

### ISSUE THREAD

**Issue by sprive** [empathicqubit/vscode-cc65-debugger#107]
**Describe the bug**
chocolately install failure because deac-riga.dl.sourceforge.net does not answer

**To Reproduce**
1. Follow Readme.md install instructions (note: chocolatey is already installed). 
2. Per readme, execute `choco install --version 3.6.0 winvice-nightly`
3. See error

**Expected behavior**
Successful installation of dependencies plus vscode-cc65-debugger

**Screenshots**
See error text at end

**Platform information (please complete the following information):**
VSCode 
Version:1.66
```
Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000
```

What version of VICE are you using? (Help menu > About VICE)

Do you have cc65 installed separately or are you using the builtin one?
If you have it installed separately, be sure you are using the one with the changes from [empathicqubit/cc65](https://github.com/empathicqubit/cc65)

OS Type (Mac OS, Windows, Linux):
OS Version:
For Windows use `Reg Query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseId`
For Mac OS use `sw_vers`
For Linux use `lsb_release -a`

```
PS C:\Users\scott> Reg Query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v ReleaseId`
ERROR: The system was unable to find the specified registry key or value.
(NOTE: Above failed. Grabbed similar info from Control Panel instead:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎11/‎14/‎2021
OS build	22000.556
Experience	Windows Feature Experience Pack 1000.22000.556.0

```

OS Architecture (for example, amd64, i686, arm, arm64):
i686

If you are able please provide your PATH:
For Windows (cmd) use `echo %PATH%`
For Mac OS/Linux use `echo $PATH`
Be sure to remove any information you consider sensitive. Replace it with REDACTED
```
Paste your PATH here
C:\Users\scott\work\cc65_a8>echo %PATH%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\msys64\mingw64\bin;C:\Program Files\gettext-iconv\bin;c:\cc65\bin;C:\Users\scott\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\scott\AppData\Local\Programs\Python\Python39\;C:\Users\scott\AppData\Local\Microsoft\WindowsApps;c:\Program Files (x86)\Java\jre1.8.0_301\bin;;C:\Users\scott\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Nmap```

**Additional context**
```
install + error
PS C:\Users\scott> choco install --version 3.6.0 winvice-nightly
>>
Chocolatey v0.11.3
Installing the following packages:
winvice-nightly
By installing, you accept licenses for the packages.
Progress: Downloading winvice-nightly 3.6.0... 100%

winvice-nightly v3.6.0 [Approved]
winvice-nightly package files install completed. Performing other installation steps.
The package winvice-nightly wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): Y

Attempt to get headers for https://deac-riga.dl.sourceforge.net/project/vice-emu/releases/binaries/windows/GTK3VICE-3.6-win64.zip failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://deac-riga.dl.sourceforge.net/project/vice-emu/releases/binaries/windows/GTK3VICE-3.6-win64.zip'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
Downloading winvice-nightly
  from 'https://deac-riga.dl.sourceforge.net/project/vice-emu/releases/binaries/windows/GTK3VICE-3.6-win64.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://deac-riga.dl.sourceforge.net/project/vice-emu/releases/binaries/windows/GTK3VICE-3.6-win64.zip'. Exception calling "GetResponse" with "0" argument(s): "Unable to connect to the remote server"
The install of winvice-nightly was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winvice-nightly\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winvice-nightly (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\winvice-nightly\tools\chocolateyinstall.ps1'.
 See log for details.
PS C:\Users\scott>
```

**Comment by empathicqubit** [comment]
Can you try this version and see if it works for you? I built it manually a few weeks ago but it hasn't been approved yet: https://community.chocolatey.org/packages/winvice-nightly/3.6.1

**Comment by empathicqubit** [comment]
Hi, please reopen this if you're still having a problem.
