### ISSUE TITLE
Encountered Error : "The output stream for this command is already redirected"

### ISSUE THREAD

**Issue by beamrider66** [empathicqubit/vscode-cc65-debugger#112]
**Describe the bug**
I tried the supplied asm-project project but it won't debug for me.

**To Reproduce**
Press F5 

**Expected behaviour**
Debugging session starts

**Actual behaviour**
Get the following error:
```
At line:1 char:1997
+ ... '||' 'echo' > '"C:\Users\adria\AppData\Local\Temp/cc65vice_make_failu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    
The output stream for this command is already redirected.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : StreamAlreadyRedirected
```

**Platform information (please complete the following information):**
Are you using VSCode or Codium?

This is on Windows under VS-Code

Version:
```

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```

**What version of VICE are you using? (Help menu > About VICE)**
3.6.1
(GTK3 3.24.31, GLib 2.70.2, Cairo 1.17.4, Pango 1.50.3)
Windows 10 
x86_64 (64-bit)

**Do you have cc65 installed separately or are you using the builtin one?**
Built in

**OS Type (Mac OS, Windows, Linux):**
Windows

**OS Version:**
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    ReleaseId    REG_SZ    2009
```

**OS Architecture (for example, amd64, i686, arm, arm64):**
64 Bit Windows

If you are able please provide your PATH:
For Windows (cmd) use `echo %PATH%`
For Mac OS/Linux use `echo $PATH`
Be sure to remove any information you consider sensitive. Replace it with REDACTED
```
 Paste your PATH here
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\GtkSharp\2.12\bin
C:\Android
C:\Program Files\Oculus\Support\oculus-runtime
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\dotnet\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files (x86)\Common Files\Acronis\VirtualFile\
C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\
C:\Program Files (x86)\Common Files\Acronis\FileProtector\
C:\Program Files (x86)\Common Files\Acronis\FileProtector64\
C:\Program Files (x86)\Common Files\Acronis\SnapAPI\
C:\Program Files\Git\cmd
C:\Program Files\nodejs\
C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
C:\Program Files (x86)\dotnet\
C:\Program Files\TortoiseGit\bin
C:\Users\adria\AppData\Local\pnpm
C:\Users\adria\AppData\Local\Programs\Python\Python38\Scripts\
C:\Users\adria\AppData\Local\Programs\Python\Python38\
C:\Users\adria\AppData\Local\Microsoft\WindowsApps
C:\Users\adria\.dotnet\tools
C:\Users\adria\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\adria\AppData\Roaming\npm
```

**Additional context**

**Comment by empathicqubit** [comment]
Please downgrade to VSCode 1.67.1. It works correctly in this version. For some reason the argument quoting is different in 1.67.2. 😒

**Comment by empathicqubit** [comment]
It seems the issue could be related to microsoft/vscode#148887

**Comment by empathicqubit** [comment]
Okay, I have a fix which I'll look into releasing tomorrow.

**Comment by beamrider66** [comment]
thanks, I'll wait for that. btw, can I confirm whether this extension works for Vic-20 development or just C64?

**Comment by empathicqubit** [comment]
VIC20 is not well tested, but it should theoretically work.

**Comment by empathicqubit** [comment]
Okay, there's a new version 6.2.0 out there on the Marketplace. It might take a little bit for it to show up.

**Comment by beamrider66** [comment]
many thanks for the quick turn-around. 

I'll take a look tomorrow.

**Comment by empathicqubit** [comment]
Do you have any other information in any of the other terminals?

**Comment by beamrider66** [comment]
Just one error - I get the following outputs:

**Building...**
```
`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6


PS C:\cbmDev\vscode-cc65asm-project>  ${env:PATH}='c:\Users\adria\.vscode\extensions\entan-gl.cc65-vice-6.2.0\dist\cc65/bin_win32_x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Android;C:\Program Files\Oculus\Support\oculus-runtime;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\TortoiseGit\bin;C:\Users\adria\AppData\Local\pnpm;C:ata\Local\pnpm;C:\Users\adria\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\adria\AppData\Local\Programs\Python\Python38\;C:\Users\adria\AppData\Local\Microsoft\WindowsApps;C:\Users\adria\.ders\adria\AppDataotnet\tools;C:\Users\adria\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\adria\AppData\Roaming\npm;C:\Tools\CLI;'; ${env:CC65_HOME}='c:\Users\adria\.vscode\extensions\entan-gl.cc65-vice-6.2.0\dODE}='1'; & 'cmd.ist\cc65'; ${env:ELECTRON_RUN_AS_NODE}='1'; & 'cmd.exe' '"/S"' '"/C"' '"make"' '"OPTIONS=mapfile,labelfile,debugfile"' '&&' 'echo' '>>' '"C:\Users\adria\AppData\Local\Temp/cc65vice_make_success_0.00254AppData\Local\Tem90776313485952"' '||' 'echo' '>>' '"C:\Users\adria\AppData\Local\Temp/cc65vice_make_failure_0.9233098569352256"'
make TARGETS=c64 all
make[1]: Entering directory `C:/cbmDev/vscode-cc65asm-project'
mkdir obj\c64
cl65 -t c64 -c --create-dep obj/c64/main.d -g -o obj/c64/main.o src/main.s
cl65 -t c64 -g --mapfile program.c64.map -Ln program.c64.lbl -Wl --dbgfile,program.c64.dbg -o program.c64 obj/c64/main.o
make[1]: Leaving directory `C:/cbmDev/vscode-cc65asm-project'
make TARGETS=pet all
make[1]: Entering directory `C:/cbmDev/vscode-cc65asm-project'
mkdir obj\pet
cl65 -t pet -c --create-dep obj/pet/main.d -g -o obj/pet/main.o src/main.s
cl65 -t pet -g --mapfile program.pet.map -Ln program.pet.lbl -Wl --dbgfile,program.pet.dbg -o program.pet obj/pet/main.o
make[1]: Leaving directory `C:/cbmDev/vscode-cc65asm-project'
PS C:\cbmDev\vscode-cc65asm-project> ^C
PS C:\cbmDev\vscode-cc65asm-project>`
```


**VICE**

```
`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\adria\AppData\Local\Programs\Microsoft VS Code>  ${env:ELECTRON_RUN_AS_NODE}='1'; & 'cmd.exe' '"/S"' '"/C"' '"C:\cbmDev\GTK3VICE-3.6.1-win64\bin\x64sc.EXE"' '"-default"' '"+sound"' '"+remotemonitor"' '"-binarymonitor"' '"-binarymonitoraddress"' '"127.0.0.1:29774"'
PS C:\Users\adria\AppData\Local\Programs\Microsoft VS Code> `

```

**VICE** (second tab for VICE?)
```
[](`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\cbmDev\vscode-cc65asm-project>  ${env:ELECTRON_RUN_AS_NODE}='1'; & 'cmd.exe' '"/S"' '"/C"' '"C:\cbmDev\GTK3VICE-3.6.1-win64\bin\x64sc.EXE"' '"-directory"' '"c:\Users\adria\.vscode\extensions\entan-gl.cc65-vice-6.2.0\dist\system"' '"-sound"' '"-iecdevice8"' '"-autostart-warp"' '"-autostartprgmode"' '"1"' '"+autostart-handle-tde"' '"-logfile"' '"C:\Users\adria\AppData\Local\Temp\cc65-vice-7284H7OmW8nH7u8B"' '"-moncommands"' '"C:\cbmDev\vscode-cc65asm-project/program.c64.lbl"' '"-remotemonitor"' '"-remotemonitoraddress"' '"127.0.0.1:29213"' '"-binarymonitor"' '"-binarymonitoraddress"' '"127.0.0.1:29776"'
PS C:\cbmDev\vscode-cc65asm-project> 
)
```

**Log Output**

 ```

`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\adria\.vscode\extensions\entan-gl.cc65-vice-6.2.0\dist>  ${env:ELECTRON_RUN_AS_NODE}='1'; & 'cmd.exe' '"/S"' '"/C"' '"powershell"' '"-Command"' '"Get-Content"' '"C:\Users\adria\AppData\Local\Temp\cc65-vice-83682rIMWmMkEkkJ"' '"-Wait"'
Get-Content : Cannot find path 'C:\Users\adria\AppData\Local\Temp\cc65-vice-83682rIMWmMkEkkJ' because it does not exist.
At line:1 char:1
+ Get-Content C:\Users\adria\AppData\Local\Temp\cc65-vice-83682rIMWmMkE ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\adria\...3682rIMWmMkEkkJ:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
PS C:\Users\adria\.vscode\extensions\entan-gl.cc65-vice-6.2.0\dist> 
 
```

**Comment by beamrider66** [comment]
As for the Vic-20 support, is there somewhere to specify xvic.exe instead of x64sc.exe ?

**Comment by beamrider66** [comment]
+ I notice you refer to .cc65-vice-6.2.0 in your script, but the latest release for Windows is 3.6.1?

**Comment by empathicqubit** [comment]
Can you please provide your output for the VIC20 run when you get the chance? I think I will add some log collection to the extension so it's easier for me to understand what's breaking

**Comment by beamrider66** [comment]
Sorry, I didn't try the Vic-20 yet. I wanted to see the baseline project you supplied working first. I have my own Vic-20  makefile to convert.

**Comment by empathicqubit** [comment]
If you need some clues, it might help to look at the c-project-template. It has more launch.json targets.

**Comment by beamrider66** [comment]
I should add that I removed the pet target and it seems to be working a little. I can see the C64 display and the source code. I don't seem to see the registers though.

**Comment by empathicqubit** [comment]
Can you try VICE 3.6.0 instead?

**Comment by beamrider66** [comment]
okay

**Comment by empathicqubit** [comment]
Another thing: You're positive that the registers group is expanded?

**Comment by beamrider66** [comment]
same result:

It works partially with only a single target, but debugging info seems to be missing all the subs are called subsub etc..

[I can't see a registers window at all, I just have the source code.](

_https://pasteboard.co/gYh1vBZm0txF.png_


 I see the following warnings:
 
 "csyms are missing from your debug file. Did you add the -g switch to your linker
and compiler? (CFLAGS and LDFLAGS at the top of the standard CC65 Makefile)"

To avoid problems, make sure you're using VICE 3.6 or later.

**Comment by empathicqubit** [comment]
Can you click the three dots button next to the launch selection, to see if you have panels turned off?

**Comment by empathicqubit** [comment]
The csyms error occurs because there are no C files in the project.

**Comment by beamrider66** [comment]
ah okay I see it down at the bottom, I was looking for it in the left hand-side like your screen shot. Thanks!

**Comment by beamrider66** [comment]
so seems to be working now for a single target at least many thanks!

**Comment by empathicqubit** [comment]
No problem. I just tripped over this on Linux:

```
>  /usr/bin/env PATH=/home/empathicqubit/.vscode/extensions/entan-gl.cc65-vice-6.2.0/dist/cc65/bin_linux_x64:/home/empathicqubit/.local/bin:/home/empathicqubit/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CC65_HOME=/home/empathicqubit/.vscode/extensions/entan-gl.cc65-vice-6.2.0/dist/cc65 ELECTRON_RUN_AS_NODE=1 make OPTIONS=mapfile,labelfile,debugfile \&\& echo \>\> /tmp/cc65vice_make_success_0.7892329504984583 \|\| echo \>\> /tmp/cc65vice_make_failure_0.9269424790883947 
make: *** Keine Regel, um „&&“ zu erstellen.  Schluss.
empathicqubit@sager-laptop:~/vscode-cc65-debugger/src/__tests__/asm-project [ git: ~ ] 
> 
```
![82944](https://user-images.githubusercontent.com/32425208/169892191-1de3d650-9900-49bd-ac1c-8cf0dad837dc.gif)

**Comment by empathicqubit** [comment]
I don't understand why Microsoft needed to change this

**Comment by empathicqubit** [comment]
@beamrider66 So it definitely is working for you with VIC now? It had worked for me when I tried it on Windows.

**Comment by beamrider66** [comment]
I haven't tried with Vic yet, will give it a go tomorrow.

**Comment by beamrider66** [comment]
> The csyms error occurs because there are no C files in the project.

will you fix this in next release?

**Comment by beamrider66** [comment]
I couldn't get it to work for the Vic-20. Can you outline what needs adding to launch.config or makefile for this? I followed you instructions but can't see anything about setting the target -  I don't want to use the standard makefile that you used as I don't understand it. Mine is much simpler.

When I press F5 it tries to use the x64 Vice and also gets the old error:

Cannot find path 'C:\Users\adria\AppData\Local\Temp\cc65-vice-83682rIMWmMkEkkJ'

**My MakeFile (abridged)**
 
```
FILESTEM := GAME
BINFILE := $(FILESTEM).prg
CFGFILE := basic-16k.cfg
HEADERS := $(wildcard src/*.inc)
OBJECTS :=  obj/startup.o  	\
			obj/main.o 		\
			obj/tables.o  	\

rebuild: clean build

build: mkOutputDirs compile 
	
compile:  $(OBJECTS)
	tools\ld65  -C $(CFGFILE)  -Ln obj/$(FILESTEM).lbl   --dbgfile obj/$(FILESTEM).dbg   -m obj/$(FILESTEM).map -o bin/$(BINFILE) $^

obj/%.o: src/%.s ${HEADERS}
	tools\ca65.exe $< -g --cpu 6502 -t vic20 --listing obj/$*.lst -o $@

mkOutputDirs: 
	- if not exist obj mkdir obj
	- if not exist bin mkdir bin

clean:
	- if  exist obj\*.*  del /F /Q obj\*.*
	- if  exist bin\*.*  del /F /Q bin\*.*
```

**Comment by beamrider66** [comment]
Another question: any way to hide the CPU cycles shown on each line of code?

**Comment by beamrider66** [comment]
I don't use CL I use separate compile and link

I couldn't see any reference for "--debug-tables" in the CA65 documentation and it's rejected by latest CA65?

-g option is only supported by LD65 not CA65?

**Comment by empathicqubit** [comment]
Here is the documentation for debug-tables. It is an option for cc65 to allow for debugging type information on struct fields and such: https://github.com/cc65/cc65/blob/master/doc/cc65.sgml#L201

**Comment by empathicqubit** [comment]
Your emulatorArgs is wrong. You have quoted two separate arguments "-memory" and "all" together.

**Comment by beamrider66** [comment]
> Here is the documentation for debug-tables. It is an option for cc65 to allow for debugging type information on struct fields and such: https://github.com/cc65/cc65/blob/master/doc/cc65.sgml#L201

okay I'm using CA65 so I guess it doesn't apply?

**Comment by empathicqubit** [comment]
I don't think so.

**Comment by beamrider66** [comment]
-memory <spec>
Specify memory configuration. (none/3k/8k/16k/24k/all) / (0/1/2/3/5) / (04/20/40/60/a0)

-model <Model>
Set VIC20 model (vic20/vic20pal/vic20ntsc, vic21)

These are the options from Xvic, so memory was ok NTSC  should have been -model vic20ntsc

**Comment by empathicqubit** [comment]
I will close this issue now and open a new one for the Linux issue, which is related to the one you reported. If you need more help it would probably be best to continue elsewhere

**Comment by beamrider66** [comment]
> The machine type is determined by the library that is used in the project. Do you see a library file in your debug file?

no this is a pure assembler project.  Would be useful to be able to set the emulator directly in the launch config and override the default?

**Comment by empathicqubit** [comment]
>  Would be useful to be able to set the emulator directly in the launch config and override the default?
Probably. I will open a new issue for it.

**Comment by empathicqubit** [comment]
>  I tried renaming xVic to x64 but still didn't work.

The arguments are different, so that won't work.

**Comment by empathicqubit** [comment]
> okay thanks for your help. I'll continue having a play to see if I can get it working.

No problem

**Comment by empathicqubit** [comment]
> > The csyms error occurs because there are no C files in the project.
> 
> will you fix this in next release?

I don't know that there is a good way to handle this. It's just a warning for the original intended use of the project. The project isn't oriented towards assembly, though it works with it okay.
