### ISSUE TITLE
set the emulator / machine type directly in the launch config and override the default

### ISSUE THREAD

**Issue by empathicqubit** [empathicqubit/vscode-cc65-debugger#115]
> The machine type is determined by the library that is used in the project. Do you see a library file in your debug file?

no this is a pure assembler project.  Would be useful to be able to set the emulator directly in the launch config and override the default?  I tried renaming xVic to x64 but still didn't work.

_Originally posted by @beamrider66 in https://github.com/empathicqubit/vscode-cc65-debugger/issues/112#issuecomment-1136329735_

**Comment by empathicqubit** [comment]
@beamrider66 This should be available once 6.3.0 publishes

**Comment by beamrider66** [comment]
thanks, I'll take a look.

**Comment by beamrider66** [comment]
Thank you for fixing this.

I can now at least launch my program and step through the code.

**Comment by beamrider66** [comment]
I've raised a bug about the error I get. 

Also, I don't get any symbols or call-stack, I didn't raise a bug as I don't know what support you have for assembler variables and call-stack?

**Comment by empathicqubit** [comment]
You will get a call stack if you use procedures, I think

**Comment by beamrider66** [comment]
thanks, what about the symbols?

In the variables window only the registers are populated and the name of my
variables always return 0.
