### ISSUE TITLE
Cannot find path error.

### ISSUE THREAD

**Issue by beamrider66** [empathicqubit/vscode-cc65-debugger#121]
Get the following on second and subsequent presses of F5. It goes away if I close and re-open VS-CODE. 

**The debugging session still works however.**

Get-Content : Cannot find path 'C:\Users\adria\AppData\Local\Temp\cc65-vice-19096Cbe4PV5A64wP' because it does not exist.
At line:1 char:1
+ Get-Content C:\Users\adria\AppData\Local\Temp\cc65-vice-19096Cbe4PV5A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\adria\...096Cbe4PV5A64wP:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by empathicqubit** [comment]
Fixed in 6.3.2.
