### ISSUE TITLE
More support for assembler please

### ISSUE THREAD

**Issue by beamrider66** [empathicqubit/vscode-cc65-debugger#123]
I would like to see more support for assembler projects. 

A majority of 8-bit development is in assembler rather than c I would expect.

I would like to see support for:

- [ ] assembler variables
- [ ] labels in tooltip
- [ ] watch window
- [ ] assembler constants/.defines in mouse tooltip
~a call-stack based on jsr/rts instructions~

I think these are all available from the VICE monitor as I used to load all of them from the .lbl file e.g.
  ld65 -Ln prog.lbl
  vice.exe -moncommands  prog.lbl 
  
  I also see them in your .dbg file.

~The other c functionality would be nice GotoDefinition, Find All References, Rename etc...~

**This is supported well enough by other extensions**

~For an idea, look at Alchemy65 that seems to offer a lot of this, but unfortunately doesn't work with VICE.~

**Comment by empathicqubit** [comment]
For additional C functionality please install Microsoft's C/C++ extension. It works well. Also see https://github.com/empathicqubit/vscode-cc65-debugger/blob/master/.vscode/c_cpp_properties.json for setup

**Comment by empathicqubit** [comment]
Please also provide a code sample and detail exactly what you are expecting from it

**Comment by empathicqubit** [comment]
For C code parsing please install the extension llvm-vs-code-extensions.vscode-clangd . This should already be recommended by the project. You also will need llvm. Easiest way to install would be `choco install llvm`. I will readd this information to the README. I used to require it for the debugger type handling to work, but I removed it because I thought it was no longer necessary.

**Comment by beamrider66** [comment]
No worries. I understand. I am also working full time and writing retro code in spare time so not sure I'll have time. I understand there's no obligation to do anything in response to feature requests etc as you are not charging for it.  

I actually ran your ASM project and did notice some of the variables listed under static+ but they don't show for my project so I will have a look and try to figure out what's different. That just leaves the call-stack missing which as you say I can look at in VICE.

Once again thanks for this.

**Comment by empathicqubit** [comment]
I added a new variable scope which may contain more of what you want. It gets included in the evaluation context, so it will show up on hover and in equations.
