### ISSUE TITLE
The selection CPU count remains on the screen when there is no selection

### ISSUE THREAD

**Issue by beamrider66** [empathicqubit/vscode-cc65-debugger#124]
The selection CPU count remains on the screen when the selection is cleared.

Personally, I think displaying this in the hover-over is sufficient.

Also, it indicates the ALT+mouse is required, but ALT doesn't seem to be necessary.

**Comment by empathicqubit** [comment]
I don't consider this a bug, but there is some general weirdness with the cycle counters that I will try to fix.

ALT+mouse isn't required, but lets you select lines individually.
![Screenshot 2022-06-01 031503](https://user-images.githubusercontent.com/32425208/171308731-68b97524-35a1-4e58-9f6e-6502ae42f6bb.png)

**Comment by beamrider66** [comment]
I would consider it a bug - you're left with a random green CPU count on the screen that has no relationship to anything? Anyway, your call.

**Comment by KlausLoeffelmann** [comment]
Also, sometimes the input buffer gets corrupted by that CPU count, and then you need to restart. A hotkey to switch it off, reset it and switch it back on again would be REALLY helpful.

**Comment by empathicqubit** [comment]
There is a toggle in the command palette @KlausLoeffelmann which you should be able to assign to a hotkey, but I'll see if I can make the rendering less obnoxious

**Comment by empathicqubit** [comment]
Okay, please check the behavior in 6.3.6 if you can. It updates more often, the main thing I'm not sure about is if it performs well.

**Comment by KlausLoeffelmann** [comment]
I'll take a look!
Thanks for updating!
