### ISSUE TITLE
Problems displaying Memory in Debugger

### ISSUE THREAD

**Issue by KlausLoeffelmann** [empathicqubit/vscode-cc65-debugger#129]
In Debug mode, CC65 - Run Tab - as I understood it - is supposed to display content based on current memory configuration. In my case, those tabs (Display, Sprites, Text, Memory) always remains empty.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/9663150/197361345-6193d063-a0b5-405e-b494-63f3e660667a.png">

<img width="705" alt="image" src="https://user-images.githubusercontent.com/9663150/197361373-8f5daba8-eab5-4c39-8c97-8d48220f5d49.png">

At the same time, the debugger displays other things like Registers and Local Variables:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/9663150/197361444-dfeb34c5-b1c9-4963-a29a-825961b0deb1.png">

I may be missing something here - but what?

**Comment by empathicqubit** [comment]
Okay, fix coming in 6.3.7
