### ISSUE TITLE
Issues installing/running the extension based on template

### ISSUE THREAD

**Issue by bjartwolf** [empathicqubit/vscode-cc65-debugger#88]
**In progres... I will update the text while I do some troubleshooting and add some more info... ** 

Hi! Following up on your [twitter message](https://twitter.com/EmpathicQubit/status/1473830316284514308). Would love to get the plugin running, I gave up after some initial attempts. 
⚠️ I might have messed up PATHs and even the plugin troubleshooting it... I think I have a clean install, but good to be aware that I did mess around a bit trying to get things to run... Will try to read the README with fresh eyes and make sure my system is farily reasonable setup...⚠️

I did have some attempts at having it run from WSL2, which I think got me into a few issues to begin with.
I am now trying to run it in VS Code on a Windows 10 only environment and I am starting fresh based on https://github.com/empathicqubit/vscode-cc65-debugger/tree/master/src/__tests__/c-project-template

I copied the files except the main.c file (I am keeping my own right now) and the .vimspector.json file as I guess it is not required.
I keep them at a separate branch https://github.com/bjartwolf/langtoncant/tree/try-vscode-cc65-debugger

My first attempt at pressing "Launch" the CC65 Vice Launch gives

![image](https://user-images.githubusercontent.com/1174441/147285513-d7265a09-4a36-41e5-9437-986f1115c513.png)

```
process_begin: CreateProcess(NULL, echo, ...) failed.
Makefile:183: pipe: No error
C:/ProgramData/chocolatey/lib/make/tools/install/bin/make.exe TARGETS=c64 all
make[1]: Entering directory 'C:/code/langtoncant'    
process_begin: CreateProcess(NULL, echo, ...) failed.
Makefile:183: pipe: No error
mkdir -p obj/c64
process_begin: CreateProcess(NULL, mkdir -p obj/c64, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:289: obj/c64] Error 2
make[1]: Leaving directory 'C:/code/langtoncant'
make: *** [Makefile:326: all] Error 2
```

Just running
```sh
make
```
or
```sh
make OPTIONS=mapfile,labelfile,debugfile
``` 
gives the same error as when I try to launch, both in PowerShell and Command Prompt.

```powershell
PS C:\code\langtoncant> C:\Users\bjart\.vscode\extensions\entan-gl.cc65-vice-5.1.2\dist\cc65\bin_win32_x64\cc65.exe --version

cc65.exe V2.19 - Git fd8d51497
```

```
❯ make --version
GNU Make 4.3
Built for Windows32
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by empathicqubit** [comment]
What happens when you try to run these commands in cmd.exe?

```sh
echo
where mkdir
```

**Comment by bjartwolf** [comment]
I realize I do not know cmd.exe very well. I used to know how to write bat files...
```cmd
C:\code\langtoncant>echo
ECHO is on.

C:\code\langtoncant>where mkdir
INFO: Could not find files for the given pattern(s).
```

**Comment by empathicqubit** [comment]
It looks like the script has determined that your system is Linux for some reason (`mkdir -p`). Do you have Git tools in your PATH? That caused some strange issues on my system and I had to remove them.

**Comment by empathicqubit** [comment]
Okay, what you posted looks correct.

**Comment by empathicqubit** [comment]
What happens if you remove `pet` from the Makefile targets? That's one thing I did to get it to work in my fork.

**Comment by bjartwolf** [comment]
I removed three git entries from the PATH, rebooted and WIN 🥳 
![image](https://user-images.githubusercontent.com/1174441/147288277-1901aee0-df5c-4dde-8b57-fb73f5674972.png)

**Comment by bjartwolf** [comment]
(I mean, we might need to figure out why, as removing git from the PATH is probably not a solution for most people in the long term...)

**Comment by empathicqubit** [comment]
Nice! I'll have to about how to handle this situation a little more.

**Comment by empathicqubit** [comment]
You shouldn't need to remove Git from the PATH, only the Unix tools it tells you not to install on the PATH because it might break things.

**Comment by empathicqubit** [comment]
Can you try it with _only_ Git on the PATH?

**Comment by empathicqubit** [comment]
That would be the `C:\Program Files\Git\cmd` folder.

**Comment by bjartwolf** [comment]
Yes, so leave the ```C:\Program Files\Git\bin``` out.

**Comment by empathicqubit** [comment]
Probably. The problematic directory is `usr\bin`, since that masks `echo`. `bin` looks like it should be okay though.

**Comment by bjartwolf** [comment]
Yes, can confirm it fails with 
```
C:\Program Files\Git\bin
C:\Program Files\Git\cmd
```
and works with ``` C:\Program Files\Git\cmd ``` in the PATH. Took a little time, had to restart to make sure the effect was there... It is easy to get false positives without deleting the build files and doing a proper restart...

**Comment by empathicqubit** [comment]
What's in your `bin` folder? I only have git bash, and sh in there.

**Comment by bjartwolf** [comment]
Same.

**Comment by bjartwolf** [comment]
(The plugin is fantastic, being able to debug like this makes the program trivial to write :) The hard part of writing it was not having a clue what is going on when there is some random bug...)

**Comment by empathicqubit** [comment]
Odd. I'll look at it a little more. Thanks for letting me know about this.

**Comment by empathicqubit** [comment]
Thanks! I'm glad it's helpful to you. ^_^

**Comment by bjartwolf** [comment]
Let me know if you want me to test something - I can not promise fast response during xmas, but have time before new year... It sounds horrible to debug, supporting linux and windows is hard enough without stuff "leaking" between the two...

**Comment by empathicqubit** [comment]
Thanks! Testing against both systems is rather hellish sometimes. :| I would like to run integration tests against Windows but it goes so slowly in Github Actions that it eventually times out.

**Comment by bjartwolf** [comment]
I was thinking of trying to run things in WSL2, maybe that in _theory_ would be easier, but then I remembered there is talking to VICE and some communication stuff going on that is probably not trivial either... And that might run in to another set of complexity.... 

With https://github.com/microsoft/wslg hopefully becoming more mainstream maybe you can ditch native support for Windows?

**Comment by empathicqubit** [comment]
I'll have to think about that. I'm not sure if running the Makefile under WSL context will be more confusing for the users, but native Windows is a kind of frustratingly inconsistent environment sometimes.

**Comment by empathicqubit** [comment]
Thanks for the plug, btw
