### ISSUE TITLE
Strange graphic distortion when running debug with Vice Plus4

### ISSUE THREAD

**Issue by perweij** [empathicqubit/vscode-cc65-debugger#89]
I am testing VS65 Debugger with the Vice Plus4 emulator.

For some reason, the emulator graphics gets strangely messed up when the program is autostarted by the IDE. I'm not sure if it's because of some bad state on my machine, or if it's there is a bug in VS65 Debugger - or perhaps I am using it wrongly.

If I copy the Vice invocation command which is shown in the internal terminal (including all arguments), and autostart the program binary which was built by codium above manually from a terminal, the graphics look good. Strange. I have a hypothesis that the problems are caused by some commands which are sent from the IDE via the remote monitor port to the emulator after the autostart.

I have created a minimal Plus4 code project that reproduces the error, and have included screenshots:
    https://github.com/perweij/plus4-debug

It should be enough to check out that project, open the directory in codium, and start the debugger.

I am running:
- Linux/amd64 Ubuntu 20.04.3
- VS65 Debugger 5.1.2
- Vice 3.6.0
- Codium 1.53.2

**Comment by empathicqubit** [comment]
When you say the emulator graphics get messed up, do you mean while running, or while paused?

**Comment by empathicqubit** [comment]
Thank you for providing your version information. :)

**Comment by empathicqubit** [comment]
Hello. I think I've traced this down and I think it's an issue with runahead. This is a trick that the debugger uses so you can see the entire next frame, but it doesn't always work because it relies on VICE's save states, which can be glitchy. Can you try disabling it?

**Comment by empathicqubit** [comment]
I'll try to see if there's an issue upstream with VICE

**Comment by empathicqubit** [comment]
I've been told that plus4 snapshots are broken in VICE, so please just set runahead to false in your settings. I'm not sure right now if I'll prevent the debugger from using them, or fix the problem in VICE.

**Comment by empathicqubit** [comment]
I changed the code recently so that it ignores the runahead setting for platforms which don't support it very well

**Comment by perweij** [comment]
Thanks! Really sorry for not following up here! Your work inspired me, and
I sort of got entangled in making a Vice-debugger myself for Emacs.

**Comment by empathicqubit** [comment]
Cool! Do you have a public link?

**Comment by perweij** [comment]
Thanks, but it’s nothing as fancy as your work I can tell you!

I will make it public once I’ve figured out how to make “preset
breakpoints” (i.e. breakpoints set before launching Vice) work satisfyingly
- it seems important especially to debug code executed by IRQ.

lör 2 juli 2022 kl. 13:34 skrev empathicqubit ***@***.***>:
