### ISSUE TITLE
vice 3.6 cannot load cc65-debugger's kernal

### ISSUE THREAD

**Issue by thabach** [empathicqubit/vscode-cc65-debugger#91]
Heya 

on running with vice 3.6: `x64sc -directory /Users/someone/.vscode/extensions/entan-gl.cc65-vice-5.1.2/dist/system/C64`

I get: `C64MEM: Error - Couldn't load kernal ROM 'kernal'`

Thx and cheers.

**Comment by empathicqubit** [comment]
That's strange. I thought I had a condition to handle 3.6 correctly. Will check soon.

**Comment by DLehenbauer** [comment]
FWIW, I had the same issue w/xPet.  Experimenting w/the generated Vice 3.6 command line, it seems to be the '-directory' argument that Vice didn't like.

I couldn't find '-directory' in the [manual](https://vice-emu.sourceforge.io/vice_3.html#SEC22), so perhaps it unsupported/removed?

**Comment by empathicqubit** [comment]
@DLehenbauer  It's supported but the structure changed, so the debugger has to correctly detect the version in order to use the right method.

I have a fix for this now, but I'll hold off on the release for a bit if you're working on the other thing this weekend.

**Comment by empathicqubit** [comment]
This should be fixed in v5.1.3. Please take a look in a few minutes.

**Comment by empathicqubit** [comment]
Going to close this. Please reopen if you continue to have issues.
